version: "3"
services:
  config-server:
    build: config-server/
    ports:
      - 3300:3300
    restart: always

  eureka-server:
    build: eureka-server/
    container_name: eureka-server
    ports:
      - 1515:1515
    restart: always

  track-service:
    build: track-service/
    ports:
      - 3300:3300
    depends_on:
      - eureka-server
      - config-server
    restart: always

  api-gateway:
    build: APIGatewayService/
    ports:
      - 8090:8090
    depends_on:
      - track-service
    restart: always

  user-service:
    build: userserviceS/
    ports:
      - 8081:8081
    restart: always

