FROM openjdk:11
EXPOSE 8090
WORKDIR /usrs/src
ADD ./target/APIGatewayService-0.0.1-SNAPSHOT.jar/usrs/src/APIGatewayService-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","APIGatewayService-0.0.1-SNAPSHOT.jar"]

